services:
  mysql:
    container_name: mysql-museum
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Anastasia02!
      MYSQL_DATABASE: museum_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped

volumes:
  mysql_data: