/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
/*
export { ExhibitionControllerService } from './services/exhibition-controller.service';
export { TicketControllerService } from './services/ticket-controller.service';
export { CustomerOrderControllerService } from './services/customer-order-controller.service';
*/
