/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderTicket } from '../models/order-ticket';
import { User } from '../models/user';
export interface CustomerOrder {
  id?: number;
  orderTickets?: Array<OrderTicket>;
  totalAmount?: number;
  user?: User;
}
