/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Ticket } from '../models/ticket';
export interface Exhibition {
  description?: string;
  id?: number;
  name?: string;
  tickets?: Array<Ticket>;
}
