/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerOrder } from '../models/customer-order';
import { Ticket } from '../models/ticket';
export interface OrderTicket {
  customerOrder?: CustomerOrder;
  id?: number;
  quantity?: number;
  ticket?: Ticket;
}
