/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Exhibition } from '../models/exhibition';
import { OrderTicket } from '../models/order-ticket';
export interface Ticket {
  description?: string;
  endTime?: string;
  exhibition?: Exhibition;
  id?: number;
  name?: string;
  orderTickets?: Array<OrderTicket>;
  price?: number;
  quantity?: number;
  startTime?: string;
  version?: number;
}
