/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Exhibition } from '../models/exhibition';
import { OrderTicket } from '../models/order-ticket';
export interface Ticket {
  description?: string;
  startTime?: string | null; // Nullable
  endTime?: string | null;   // Nullable
  exhibition?: Exhibition;
  id: number;
  name?: string;
  orderTickets?: Array<OrderTicket>;
  price?: number;
  quantity?: number;
  version?: number;
}

