/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerOrder } from '../models/customer-order';
import { GrantedAuthority } from '../models/granted-authority';
export interface User {
  authorities?: Array<GrantedAuthority>;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  password?: string;
  purchases?: Array<CustomerOrder>;
  role?: 'ROLE_ADMIN' | 'ROLE_USER' | 'ROLE_GUEST';
  username?: string;
}
